server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    location /api/embed {
        proxy_pass http://embedding:8000/embed;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/solr/ {
        proxy_pass http://solr:8983/solr/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/insert {
        proxy_pass http://embedding:8000/insert;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/search {
        proxy_pass http://embedding:8000/search;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/clear {
        proxy_pass http://embedding:8000/clear;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
